server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 路由id，可以随意指定
        - id: user-service-route
          # 代理的服务地址
          uri: http://127.0.0.1:9091
          # 路由断言：可以匹配映射路径
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/user
      # 默认过滤器，对所有的请求生效
      default-filters:
        # 添加一个响应头
        - AddResponseHeader=X-Response-Foo,Bar


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka
  instance:
    prefer-ip-address: true